// ----------------------------------------------------
// DASHBOARD REGLEMENTS 
/* =================================     CUMULE       ============================= */

const queryR1 = `
    SELECT
    SUM(CASE WHEN D.ANNEE = EXTRACT (YEAR FROM CURRENT_DATE) -1 THEN REGL.MONTREGL ELSE 0 END) AS regl_annee_en_cours,
    SUM(CASE WHEN D.ANNEE =  EXTRACT (YEAR FROM CURRENT_DATE) - 2 THEN REGL.MONTREGL ELSE 0 END) AS regl_annee_prec
    FROM
    FAIT_REGLEMENT REGL, DIM_DATE D
    WHERE
    REGL.DATE_KEY = D.DATE_KEY
    AND D.MOIS < EXTRACT(MONTH FROM CURRENT_DATE)
    `
const queryR1Exception = `
    SELECT
    SUM(CASE WHEN D.ANNEE = EXTRACT (YEAR FROM CURRENT_DATE) -2 THEN REGL.MONTREGL  ELSE 0 END) AS regl_annee_en_cours,
    SUM(CASE WHEN D.ANNEE =  EXTRACT (YEAR FROM CURRENT_DATE) - 3 THEN REGL.MONTREGL ELSE 0 END) AS regl_annee_prec
    FROM
    FAIT_REGLEMENT REGL, DIM_DATE D
    WHERE
    REGL.DATE_KEY = D.DATE_KEY
    AND D.MOIS <= 12
    `
const queryR2 = `
    SELECT
    INTER.LIBTYPIN,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE) - 1 THEN REGL.MONTREGL ELSE 0 END) AS regl_annee_en_cours,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE) - 2 THEN REGL.MONTREGL ELSE 0 END) AS regl_annee_prec
    FROM
        FAIT_REGLEMENT REGL, DIM_INTERMEDIAIRE inter, DIM_DATE d
    WHERE
        REGL.INTERMEDIAIRE_KEY = INTER.INTERMEDIAIRE_KEY
        AND REGL.DATE_KEY = d.DATE_KEY
        AND D.MOIS < EXTRACT(MONTH FROM CURRENT_DATE) 
    GROUP BY
        INTER.LIBTYPIN
    ORDER BY
        regl_annee_prec DESC
    `
const queryR2Exception =  `
    SELECT
    INTER.LIBTYPIN,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE) -2 THEN REGL.MONTREGL  ELSE 0 END) AS regl_annee_en_cours,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE)-3 THEN REGL.MONTREGL  ELSE 0 END) AS regl_annee_prec
    FROM
        FAIT_REGLEMENT REGL, DIM_INTERMEDIAIRE inter, DIM_DATE d
    WHERE
        REGL.INTERMEDIAIRE_KEY = INTER.INTERMEDIAIRE_KEY
        AND REGL.DATE_KEY = d.DATE_KEY
        AND D.MOIS <= 12
    GROUP BY
        INTER.LIBTYPIN
    ORDER BY
        regl_annee_prec DESC
    `
const queryR3 = `
    SELECT CAT.libebran,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE) -1 THEN REGL.MONTREGL ELSE 0 END) AS regl_annee_en_cours,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE)-2 THEN REGL.MONTREGL ELSE 0 END) AS regl_annee_prec
    FROM
        FAIT_REGLEMENT REGL, DIM_CATEGORIE CAT, DIM_DATE d 
    WHERE
        REGL.CATEGORIE_KEY = CAT.CATEGORIE_KEY
        AND REGL.DATE_KEY = d.DATE_KEY
        AND D.MOIS < EXTRACT (MONTH FROM CURRENT_DATE ) 
    GROUP BY
        CAT.libebran
    ORDER BY
    regl_annee_prec ASC
    `    
const queryR3Exception = `
    SELECT CAT.libebran,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE)-2 THEN REGL.MONTREGL ELSE 0 END) AS regl_annee_en_cours,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE)-3 THEN REGL.MONTREGL ELSE 0 END) AS regl_annee_prec
    FROM
        FAIT_REGLEMENT REGL, DIM_CATEGORIE CAT, DIM_DATE d 
    WHERE
        REGL.CATEGORIE_KEY = CAT.CATEGORIE_KEY
        AND REGL.DATE_KEY = d.DATE_KEY
        AND D.MOIS <= 12
    GROUP BY
        CAT.libebran
    ORDER BY
    regl_annee_prec ASC
    `
const queryR4  = `
    SELECT D.ANNEE, D.LIBMOIS, CAT.LIBECATE, INTER.LIBTYPIN ,  sum( REGL.MONTREGL  )  as s
    FROM FAIT_REGLEMENT REGL, DIM_INTERMEDIAIRE inter, DIM_CATEGORIE cat, DIM_DATE d
    WHERE REGL.CATEGORIE_KEY = CAT.CATEGORIE_KEY
    AND REGL.INTERMEDIAIRE_KEY = INTER.INTERMEDIAIRE_KEY
    AND  REGL.DATE_KEY =  D.DATE_KEY
    AND D.MOIS < EXTRACT (MONTH from CURRENT_DATE)
    AND D.ANNEE = EXTRACT (YEAR FROM CURRENT_DATE) -1
    GROUP BY D.ANNEE, D.LIBMOIS, CAT.LIBECATE, INTER.LIBTYPIN
    ORDER BY s desc
    `
const queryR4Exception = `
    SELECT D.ANNEE, D.LIBMOIS, CAT.LIBECATE, INTER.LIBTYPIN , sum( REGL.MONTREGL)  as s
    FROM FAIT_REGLEMENT REGL, DIM_INTERMEDIAIRE inter, DIM_CATEGORIE cat, DIM_DATE d
    WHERE REGL.CATEGORIE_KEY = CAT.CATEGORIE_KEY
    AND REGL.INTERMEDIAIRE_KEY = INTER.INTERMEDIAIRE_KEY
    AND  REGL.DATE_KEY =  D.DATE_KEY
    AND D.MOIS <= 12
    AND D.ANNEE = EXTRACT (YEAR FROM CURRENT_DATE) -2
    GROUP BY D.ANNEE, D.LIBMOIS, CAT.LIBECATE, INTER.LIBTYPIN
    ORDER BY s desc
    `
const queryR5 = `
    SELECT ((regl_annee_en_cours - regl_annee_prec) / regl_annee_prec) AS pourcentage
    FROM (
       SELECT
        SUM(CASE WHEN D.ANNEE = EXTRACT (YEAR FROM CURRENT_DATE) -1 THEN REGL.MONTREGL  ELSE 0 END) AS regl_annee_en_cours,
        SUM(CASE WHEN D.ANNEE =  EXTRACT (YEAR FROM CURRENT_DATE) - 2 THEN REGL.MONTREGL ELSE 0 END) AS regl_annee_prec
        FROM
        FAIT_REGLEMENT REGL, DIM_DATE D
        WHERE
        REGL.DATE_KEY = D.DATE_KEY
        AND D.MOIS <= 12  
        )`
const queryR5Exception = `
    SELECT ((regl_annee_en_cours - regl_annee_prec) / regl_annee_prec) AS pourcentage
    FROM (
    SELECT
    SUM(CASE WHEN D.ANNEE = EXTRACT (YEAR FROM CURRENT_DATE) -2 THEN REGL.MONTREGL  ELSE 0 END) AS regl_annee_en_cours,
    SUM(CASE WHEN D.ANNEE =  EXTRACT (YEAR FROM CURRENT_DATE) - 3 THEN REGL.MONTREGL ELSE 0 END) AS regl_annee_prec
    FROM
    FAIT_REGLEMENT REGL, DIM_DATE D
    WHERE
    REGL.DATE_KEY = D.DATE_KEY
    AND D.MOIS <= 12  
    )
    `
/* =================================     MOIS       ============================= */

const queryR1Mois = `
    SELECT
    SUM(CASE WHEN D.ANNEE = EXTRACT (YEAR FROM CURRENT_DATE) -1 THEN REGL.MONTREGL ELSE 0 END) AS regl_annee_en_cours,
    SUM(CASE WHEN D.ANNEE =  EXTRACT (YEAR FROM CURRENT_DATE) - 2 THEN REGL.MONTREGL ELSE 0 END) AS regl_annee_prec
    FROM
    FAIT_REGLEMENT REGL, DIM_DATE D
    WHERE
    REGL.DATE_KEY = D.DATE_KEY
    AND D.MOIS = EXTRACT(MONTH FROM CURRENT_DATE) - 1
    `
const queryR1MoisException = `
    SELECT
    SUM(CASE WHEN D.ANNEE = EXTRACT (YEAR FROM CURRENT_DATE) -2 THEN REGL.MONTREGL   ELSE 0 END) AS regl_annee_en_cours,
    SUM(CASE WHEN D.ANNEE =  EXTRACT (YEAR FROM CURRENT_DATE) - 3 THEN REGL.MONTREGL  ELSE 0 END) AS regl_annee_prec
    FROM
    FAIT_REGLEMENT REGL, DIM_DATE D
    WHERE
    REGL.DATE_KEY = D.DATE_KEY
    AND D.MOIS = 12
    `
const queryR2Mois = `
    SELECT
    INTER.LIBTYPIN,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE) - 1 THEN REGL.MONTREGL  ELSE 0 END) AS regl_annee_en_cours,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE) - 2 THEN REGL.MONTREGL ELSE 0 END) AS regl_annee_prec
    FROM
        FAIT_REGLEMENT REGL, DIM_INTERMEDIAIRE inter, DIM_DATE d
    WHERE
        REGL.INTERMEDIAIRE_KEY = INTER.INTERMEDIAIRE_KEY
        AND REGL.DATE_KEY = d.DATE_KEY
        AND D.MOIS = EXTRACT(MONTH FROM CURRENT_DATE) - 1
    GROUP BY
        INTER.LIBTYPIN
    ORDER BY
        regl_annee_prec DESC
    `
const queryR2MoisException =  `
    SELECT
    INTER.LIBTYPIN,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE) -2 THEN REGL.MONTREGL  ELSE 0 END) AS regl_annee_en_cours,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE)-3 THEN REGL.MONTREGL ELSE 0 END) AS regl_annee_prec
    FROM
        FAIT_REGLEMENT REGL, DIM_INTERMEDIAIRE inter, DIM_DATE d
    WHERE
        REGL.INTERMEDIAIRE_KEY = INTER.INTERMEDIAIRE_KEY
        AND REGL.DATE_KEY = d.DATE_KEY
        AND D.MOIS = 12
    GROUP BY
        INTER.LIBTYPIN
    ORDER BY
        regl_annee_prec DESC
    `
const queryR3Mois = `
    SELECT CAT.libebran,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE) -1 THEN REGL.MONTREGL  ELSE 0 END) AS regl_annee_en_cours,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE)-2 THEN REGL.MONTREGL  ELSE 0 END) AS regl_annee_prec
    FROM
        FAIT_REGLEMENT REGL, DIM_CATEGORIE CAT, DIM_DATE d 
    WHERE
        REGL.CATEGORIE_KEY = CAT.CATEGORIE_KEY
        AND REGL.DATE_KEY = d.DATE_KEY
        AND D.MOIS = EXTRACT (MONTH FROM CURRENT_DATE ) -1
    GROUP BY
        CAT.libebran
    ORDER BY
    regl_annee_prec ASC
    `    
const queryR3MoisException = `
    SELECT CAT.libebran,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE)-2 THEN REGL.MONTREGL  ELSE 0 END) AS regl_annee_en_cours,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE)-3 THEN REGL.MONTREGL ELSE 0 END) AS regl_annee_prec
    FROM
        FAIT_REGLEMENT REGL, DIM_CATEGORIE CAT, DIM_DATE d 
    WHERE
        REGL.CATEGORIE_KEY = CAT.CATEGORIE_KEY
        AND REGL.DATE_KEY = d.DATE_KEY
        AND D.MOIS = 12
    GROUP BY
        CAT.libebran
    ORDER BY
    regl_annee_prec ASC
    `
const queryR4Mois  = `
    SELECT D.ANNEE, D.LIBMOIS, CAT.LIBECATE, INTER.LIBTYPIN ,  sum( REGL.MONTREGL  )  as s
    FROM FAIT_REGLEMENT REGL, DIM_INTERMEDIAIRE inter, DIM_CATEGORIE cat, DIM_DATE d
    WHERE REGL.CATEGORIE_KEY = CAT.CATEGORIE_KEY
    AND REGL.INTERMEDIAIRE_KEY = INTER.INTERMEDIAIRE_KEY
    AND  REGL.DATE_KEY =  D.DATE_KEY
    AND D.MOIS = EXTRACT (MONTH from CURRENT_DATE) -1
    AND D.ANNEE = EXTRACT (YEAR FROM CURRENT_DATE) -1
    GROUP BY D.ANNEE, D.LIBMOIS, CAT.LIBECATE, INTER.LIBTYPIN
    ORDER BY s desc 
    `
const queryR4MoisException = `
    SELECT D.ANNEE, D.LIBMOIS, CAT.LIBECATE, INTER.LIBTYPIN , sum( REGL.MONTREGL )  as s
    FROM FAIT_REGLEMENT REGL, DIM_INTERMEDIAIRE inter, DIM_CATEGORIE cat, DIM_DATE d
    WHERE REGL.CATEGORIE_KEY = CAT.CATEGORIE_KEY
    AND REGL.INTERMEDIAIRE_KEY = INTER.INTERMEDIAIRE_KEY
    AND  REGL.DATE_KEY =  D.DATE_KEY
    AND D.MOIS = 12
    AND D.ANNEE = EXTRACT (YEAR FROM CURRENT_DATE) -2
    GROUP BY D.ANNEE, D.LIBMOIS, CAT.LIBECATE, INTER.LIBTYPIN
    ORDER BY s desc
    `
const queryR5Mois = `
    SELECT ((regl_annee_en_cours - regl_annee_prec) / regl_annee_prec) AS pourcentage
    FROM (
       SELECT
        SUM(CASE WHEN D.ANNEE = EXTRACT (YEAR FROM CURRENT_DATE) -1 THEN REGL.MONTREGL  ELSE 0 END) AS regl_annee_en_cours,
        SUM(CASE WHEN D.ANNEE =  EXTRACT (YEAR FROM CURRENT_DATE) - 2 THEN REGL.MONTREGL ELSE 0 END) AS regl_annee_prec
        FROM
        FAIT_REGLEMENT REGL, DIM_DATE D
        WHERE
        REGL.DATE_KEY = D.DATE_KEY
        AND D.MOIS = 12  
        )`
const queryR5MoisException = `
    SELECT ((regl_annee_en_cours - regl_annee_prec) / regl_annee_prec) AS pourcentage
    FROM (
    SELECT
    SUM(CASE WHEN D.ANNEE = EXTRACT (YEAR FROM CURRENT_DATE) -2 THEN REGL.MONTREGL  ELSE 0 END) AS regl_annee_en_cours,
    SUM(CASE WHEN D.ANNEE =  EXTRACT (YEAR FROM CURRENT_DATE) - 3 THEN REGL.MONTREGL ELSE 0 END) AS regl_annee_prec
    FROM
    FAIT_REGLEMENT REGL, DIM_DATE D
    WHERE
    REGL.DATE_KEY = D.DATE_KEY
    AND D.MOIS = 12  
    )
    `


// ----------------------------------------------------
// DASHBOARD Chiffre d'Affaires
/* =================================     CUMULE       ============================= */

const queryCA1 = `
    SELECT
    SUM(CASE WHEN D.ANNEE = EXTRACT (YEAR FROM CURRENT_DATE) -1 THEN PROD.CA ELSE 0 END) AS annee_en_cours,
    SUM(CASE WHEN D.ANNEE =  EXTRACT (YEAR FROM CURRENT_DATE) - 2 THEN PROD.CA ELSE 0 END) AS annee_prec
    FROM
    FAIT_PRODUCTION PROD , DIM_DATE D
    WHERE
    PROD.DATE_KEY = D.DATE_KEY
    AND D.MOIS < EXTRACT(MONTH FROM CURRENT_DATE)
    `;
const queryCA1Exception = `
    SELECT
    SUM(CASE WHEN D.ANNEE = EXTRACT (YEAR FROM CURRENT_DATE) -2 THEN PROD.CA ELSE 0 END) AS annee_en_cours,
    SUM(CASE WHEN D.ANNEE =  EXTRACT (YEAR FROM CURRENT_DATE) -3 THEN PROD.CA ELSE 0 END) AS annee_prec
    FROM
    FAIT_PRODUCTION PROD, DIM_DATE D
    WHERE
    PROD.DATE_KEY = D.DATE_KEY
    AND D.MOIS <= 12
    `;
const queryCA2 = `
    SELECT
    INTER.LIBTYPIN,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE) - 1 THEN PROD.CA ELSE 0 END) AS annee_en_cours,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE) - 2 THEN PROD.CA ELSE 0 END) AS annee_prec
    FROM
      FAIT_PRODUCTION PROD, DIM_INTERMEDIAIRE inter, DIM_DATE d
    WHERE
        PROD.INTERMEDIAIRE_KEY = INTER.INTERMEDIAIRE_KEY
        AND PROD.DATE_KEY = d.DATE_KEY
        AND D.MOIS < EXTRACT(MONTH FROM CURRENT_DATE) 
    GROUP BY
        INTER.LIBTYPIN
    ORDER BY
        annee_prec DESC
    `;
const queryCA2Exception = `
    SELECT
    INTER.LIBTYPIN,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE) - 2 THEN PROD.CA ELSE 0 END) AS annee_en_cours,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE) - 3 THEN PROD.CA ELSE 0 END) AS annee_prec
    FROM
      FAIT_PRODUCTION PROD, DIM_INTERMEDIAIRE inter, DIM_DATE d
    WHERE
        PROD.INTERMEDIAIRE_KEY = INTER.INTERMEDIAIRE_KEY
        AND PROD.DATE_KEY = d.DATE_KEY
        AND D.MOIS <= 12
    GROUP BY
        INTER.LIBTYPIN
    ORDER BY
    annee_prec DESC
    `;
const queryCA3 = `
    SELECT CAT.libebran,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE) -1 THEN PROD.CA ELSE 0 END) AS annee_en_cours,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE)-2 THEN PROD.CA ELSE 0 END) AS annee_prec
    FROM
    FAIT_PRODUCTION PROD, DIM_CATEGORIE CAT, DIM_DATE d 
    WHERE
        PROD.CATEGORIE_KEY = CAT.CATEGORIE_KEY
        AND PROD.DATE_KEY = d.DATE_KEY
        AND D.MOIS < EXTRACT (MONTH FROM CURRENT_DATE ) 
    GROUP BY
        CAT.libebran
    ORDER BY
    annee_prec ASC
    `;
const queryCA3Exception = `
    SELECT CAT.libebran,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE)-2 THEN PROD.CA ELSE 0 END) AS annee_en_cours,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE)-3 THEN PROD.CA ELSE 0 END) AS annee_prec
    FROM
      FAIT_PRODUCTION PROD, DIM_CATEGORIE CAT, DIM_DATE d 
    WHERE
        PROD.CATEGORIE_KEY = CAT.CATEGORIE_KEY
        AND PROD.DATE_KEY = d.DATE_KEY
        AND D.MOIS <= 12
    GROUP BY
        CAT.libebran
    ORDER BY
    annee_prec ASC
    `;
const queryCA4 = `
    SELECT D.ANNEE, D.LIBMOIS, CAT.LIBECATE, INTER.LIBTYPIN ,  sum( PROD.CA  )  as s
    FROM FAIT_PRODUCTION PROD, DIM_INTERMEDIAIRE inter, DIM_CATEGORIE cat, DIM_DATE d
    WHERE PROD.CATEGORIE_KEY = CAT.CATEGORIE_KEY
    AND PROD.INTERMEDIAIRE_KEY = INTER.INTERMEDIAIRE_KEY
    AND  PROD.DATE_KEY =  D.DATE_KEY
    AND D.MOIS < EXTRACT (MONTH from CURRENT_DATE)
    AND D.ANNEE = EXTRACT (YEAR FROM CURRENT_DATE) -1
    GROUP BY D.ANNEE, D.LIBMOIS, CAT.LIBECATE, INTER.LIBTYPIN
    ORDER BY s desc
    `;
const queryCA4Exception = `
    SELECT D.ANNEE, D.LIBMOIS, CAT.LIBECATE, INTER.LIBTYPIN , sum( PROD.CA)  as s
    FROM FAIT_PRODUCTION PROD, DIM_INTERMEDIAIRE inter, DIM_CATEGORIE cat, DIM_DATE d
    WHERE PROD.CATEGORIE_KEY = CAT.CATEGORIE_KEY
    AND PROD.INTERMEDIAIRE_KEY = INTER.INTERMEDIAIRE_KEY
    AND  PROD.DATE_KEY =  D.DATE_KEY
    AND D.MOIS <= 12
    AND D.ANNEE = EXTRACT (YEAR FROM CURRENT_DATE) -2
    GROUP BY D.ANNEE, D.LIBMOIS, CAT.LIBECATE, INTER.LIBTYPIN
    ORDER BY s desc
    `;
const queryCA5 = `
    SELECT ((annee_en_cours - annee_prec) / annee_prec) AS pourcentage
    FROM (
      SELECT
        SUM(CASE WHEN D.ANNEE = EXTRACT (YEAR FROM CURRENT_DATE) -1 THEN PROD.CA  ELSE 0 END) AS annee_en_cours,
        SUM(CASE WHEN D.ANNEE =  EXTRACT (YEAR FROM CURRENT_DATE) - 2 THEN PROD.CA ELSE 0 END) AS annee_prec
        FROM
        FAIT_PRODUCTION PROD, DIM_DATE D
        WHERE
        PROD.DATE_KEY = D.DATE_KEY
        AND D.MOIS < EXTRACT (MONTH from CURRENT_DATE)
        )`;
const queryCA5Exception = `
    SELECT ((annee_en_cours - annee_prec) / annee_prec) AS pourcentage
    FROM (
    SELECT
    SUM(CASE WHEN D.ANNEE = EXTRACT (YEAR FROM CURRENT_DATE) -2 THEN PROD.CA  ELSE 0 END) AS annee_en_cours,
    SUM(CASE WHEN D.ANNEE =  EXTRACT (YEAR FROM CURRENT_DATE) - 3 THEN PROD.CA ELSE 0 END) AS annee_prec
    FROM
    FAIT_PRODUCTION PROD, DIM_DATE D
    WHERE
    PROD.DATE_KEY = D.DATE_KEY
    AND D.MOIS <= 12  
    )
    `;
/* =================================     MOIS       ============================= */

const queryCA1Mois = `
    SELECT
    SUM(CASE WHEN D.ANNEE = EXTRACT (YEAR FROM CURRENT_DATE) -1 THEN PROD.CA ELSE 0 END) AS annee_en_cours,
    SUM(CASE WHEN D.ANNEE =  EXTRACT (YEAR FROM CURRENT_DATE) - 2 THEN PROD.CA ELSE 0 END) AS annee_prec
    FROM
    FAIT_PRODUCTION PROD, DIM_DATE D
    WHERE
    PROD.DATE_KEY = D.DATE_KEY
    AND D.MOIS = EXTRACT(MONTH FROM CURRENT_DATE) - 1
    `;
const queryCA1MoisException = `
    SELECT
    SUM(CASE WHEN D.ANNEE = EXTRACT (YEAR FROM CURRENT_DATE) -2 THEN PROD.CA   ELSE 0 END) AS annee_en_cours,
    SUM(CASE WHEN D.ANNEE =  EXTRACT (YEAR FROM CURRENT_DATE) - 3 THEN PROD.CA  ELSE 0 END) AS annee_prec
    FROM
    FAIT_PRODUCTION PROD, DIM_DATE D
    WHERE
    PROD.DATE_KEY = D.DATE_KEY
    AND D.MOIS = 12
    `;
const queryCA2Mois = `
    SELECT
    INTER.LIBTYPIN,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE) - 1 THEN PROD.CA  ELSE 0 END) AS annee_en_cours,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE) - 2 THEN PROD.CA ELSE 0 END) AS annee_prec
    FROM
        FAIT_PRODUCTION PROD, DIM_INTERMEDIAIRE inter, DIM_DATE d
    WHERE
        PROD.INTERMEDIAIRE_KEY = INTER.INTERMEDIAIRE_KEY
        AND PROD.DATE_KEY = d.DATE_KEY
        AND D.MOIS = EXTRACT(MONTH FROM CURRENT_DATE) - 1
    GROUP BY
        INTER.LIBTYPIN
    ORDER BY
        annee_prec DESC
    `;
const queryCA2MoisException = `
    SELECT
    INTER.LIBTYPIN,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE) -2 THEN PROD.CA  ELSE 0 END) AS annee_en_cours,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE)-3 THEN PROD.CA ELSE 0 END) AS annee_prec
    FROM
        FAIT_PRODUCTION PROD, DIM_INTERMEDIAIRE inter, DIM_DATE d
    WHERE
        PROD.INTERMEDIAIRE_KEY = INTER.INTERMEDIAIRE_KEY
        AND PROD.DATE_KEY = d.DATE_KEY
        AND D.MOIS = 12
    GROUP BY
        INTER.LIBTYPIN
    ORDER BY
        annee_prec DESC
    `;
const queryCA3Mois = `
    SELECT CAT.libebran,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE) -1 THEN PROD.CA  ELSE 0 END) AS annee_en_cours,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE)-2 THEN PROD.CA  ELSE 0 END) AS annee_prec
    FROM
        FAIT_PRODUCTION PROD, DIM_CATEGORIE CAT, DIM_DATE d 
    WHERE
        PROD.CATEGORIE_KEY = CAT.CATEGORIE_KEY
        AND PROD.DATE_KEY = d.DATE_KEY
        AND D.MOIS = EXTRACT (MONTH FROM CURRENT_DATE ) -1
    GROUP BY
        CAT.libebran
    ORDER BY
    annee_prec ASC
    `;
const queryCA3MoisException = `
    SELECT CAT.libebran,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE)-2 THEN PROD.CA  ELSE 0 END) AS annee_en_cours,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE)-3 THEN PROD.CA ELSE 0 END) AS annee_prec
    FROM
        FAIT_PRODUCTION PROD, DIM_CATEGORIE CAT, DIM_DATE d 
    WHERE
        PROD.CATEGORIE_KEY = CAT.CATEGORIE_KEY
        AND PROD.DATE_KEY = d.DATE_KEY
        AND D.MOIS = 12
    GROUP BY
        CAT.libebran
    ORDER BY
    annee_prec ASC
    `;
const queryCA4Mois = `
    SELECT D.ANNEE, D.LIBMOIS, CAT.LIBECATE, INTER.LIBTYPIN ,  sum( PROD.CA  )  as s
    FROM FAIT_PRODUCTION PROD, DIM_INTERMEDIAIRE inter, DIM_CATEGORIE cat, DIM_DATE d
    WHERE PROD.CATEGORIE_KEY = CAT.CATEGORIE_KEY
    AND PROD.INTERMEDIAIRE_KEY = INTER.INTERMEDIAIRE_KEY
    AND  PROD.DATE_KEY =  D.DATE_KEY
    AND D.MOIS = EXTRACT (MONTH from CURRENT_DATE) -1
    AND D.ANNEE = EXTRACT (YEAR FROM CURRENT_DATE) -1
    GROUP BY D.ANNEE, D.LIBMOIS, CAT.LIBECATE, INTER.LIBTYPIN
    ORDER BY s desc 
    `;
const queryCA4MoisException = `
    SELECT D.ANNEE, D.LIBMOIS, CAT.LIBECATE, INTER.LIBTYPIN , sum( PROD.CA )  as s
    FROM FAIT_PRODUCTION PROD, DIM_INTERMEDIAIRE inter, DIM_CATEGORIE cat, DIM_DATE d
    WHERE PROD.CATEGORIE_KEY = CAT.CATEGORIE_KEY
    AND PROD.INTERMEDIAIRE_KEY = INTER.INTERMEDIAIRE_KEY
    AND  PROD.DATE_KEY =  D.DATE_KEY
    AND D.MOIS = 12
    AND D.ANNEE = EXTRACT (YEAR FROM CURRENT_DATE) -2
    GROUP BY D.ANNEE, D.LIBMOIS, CAT.LIBECATE, INTER.LIBTYPIN
    ORDER BY s desc
    `;
const queryCA5Mois = `
    SELECT ((annee_en_cours - annee_prec) / annee_prec) AS pourcentage
    FROM (
       SELECT
        SUM(CASE WHEN D.ANNEE = EXTRACT (YEAR FROM CURRENT_DATE) -1 THEN PROD.CA  ELSE 0 END) AS annee_en_cours,
        SUM(CASE WHEN D.ANNEE =  EXTRACT (YEAR FROM CURRENT_DATE) - 2 THEN PROD.CA ELSE 0 END) AS annee_prec
        FROM
        FAIT_PRODUCTION PROD, DIM_DATE D
        WHERE
        PROD.DATE_KEY = D.DATE_KEY
        AND D.MOIS = EXTRACT (MONTH from CURRENT_DATE) -1
        )`;
const queryCA5MoisException = `
    SELECT ((annee_en_cours - annee_prec) / annee_prec) AS pourcentage
    FROM (
    SELECT
    SUM(CASE WHEN D.ANNEE = EXTRACT (YEAR FROM CURRENT_DATE) -2 THEN PROD.CA  ELSE 0 END) AS annee_en_cours,
    SUM(CASE WHEN D.ANNEE =  EXTRACT (YEAR FROM CURRENT_DATE) - 3 THEN PROD.CA ELSE 0 END) AS annee_prec
    FROM
    FAIT_PRODUCTION PROD, DIM_DATE D
    WHERE
    PROD.DATE_KEY = D.DATE_KEY
    AND D.MOIS = 12  
    )
    `;




// ----------------------------------------------------
// DASHBOARD Contrats
/* =================================     CUMULE       ============================= */

const queryC1 = `
    SELECT
    SUM(CASE WHEN D.ANNEE = EXTRACT (YEAR FROM CURRENT_DATE) -1 THEN ( PROD.AFFNOUVELLE + PROD.RENOUVELLEMENT ) ELSE 0 END) AS annee_en_cours,
    SUM(CASE WHEN D.ANNEE =  EXTRACT (YEAR FROM CURRENT_DATE) - 2 THEN ( PROD.AFFNOUVELLE + PROD.RENOUVELLEMENT ) ELSE 0 END) AS annee_prec
    FROM
    FAIT_PRODUCTION PROD , DIM_DATE D
    WHERE
    PROD.DATE_KEY = D.DATE_KEY
    AND D.MOIS < EXTRACT(MONTH FROM CURRENT_DATE)
    `;
const queryC1Exception = `
    SELECT
    SUM(CASE WHEN D.ANNEE = EXTRACT (YEAR FROM CURRENT_DATE) -2 THEN ( PROD.AFFNOUVELLE + PROD.RENOUVELLEMENT ) ELSE 0 END) AS annee_en_cours,
    SUM(CASE WHEN D.ANNEE =  EXTRACT (YEAR FROM CURRENT_DATE) -3 THEN ( PROD.AFFNOUVELLE + PROD.RENOUVELLEMENT ) ELSE 0 END) AS annee_prec
    FROM
    FAIT_PRODUCTION PROD, DIM_DATE D
    WHERE
    PROD.DATE_KEY = D.DATE_KEY
    AND D.MOIS <= 12
    `;
const queryC2 = `
    SELECT
    INTER.LIBTYPIN,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE) - 1 THEN ( PROD.AFFNOUVELLE + PROD.RENOUVELLEMENT ) ELSE 0 END) AS annee_en_cours,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE) - 2 THEN ( PROD.AFFNOUVELLE + PROD.RENOUVELLEMENT ) ELSE 0 END) AS annee_prec
    FROM
      FAIT_PRODUCTION PROD, DIM_INTERMEDIAIRE inter, DIM_DATE d
    WHERE
        PROD.INTERMEDIAIRE_KEY = INTER.INTERMEDIAIRE_KEY
        AND PROD.DATE_KEY = d.DATE_KEY
        AND D.MOIS < EXTRACT(MONTH FROM CURRENT_DATE) 
    GROUP BY
        INTER.LIBTYPIN
    ORDER BY
        annee_prec DESC
    `;
const queryC2Exception = `
    SELECT
    INTER.LIBTYPIN,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE) - 2 THEN ( PROD.AFFNOUVELLE + PROD.RENOUVELLEMENT ) ELSE 0 END) AS annee_en_cours,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE) - 3 THEN ( PROD.AFFNOUVELLE + PROD.RENOUVELLEMENT ) ELSE 0 END) AS annee_prec
    FROM
      FAIT_PRODUCTION PROD, DIM_INTERMEDIAIRE inter, DIM_DATE d
    WHERE
        PROD.INTERMEDIAIRE_KEY = INTER.INTERMEDIAIRE_KEY
        AND PROD.DATE_KEY = d.DATE_KEY
        AND D.MOIS <= 12
    GROUP BY
        INTER.LIBTYPIN
    ORDER BY
    annee_prec DESC
    `;
const queryC3 = `
    SELECT CAT.libebran,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE) -1 THEN ( PROD.AFFNOUVELLE + PROD.RENOUVELLEMENT ) ELSE 0 END) AS annee_en_cours,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE)-2 THEN ( PROD.AFFNOUVELLE + PROD.RENOUVELLEMENT ) ELSE 0 END) AS annee_prec
    FROM
    FAIT_PRODUCTION PROD, DIM_CATEGORIE CAT, DIM_DATE d 
    WHERE
        PROD.CATEGORIE_KEY = CAT.CATEGORIE_KEY
        AND PROD.DATE_KEY = d.DATE_KEY
        AND D.MOIS < EXTRACT (MONTH FROM CURRENT_DATE ) 
    GROUP BY
        CAT.libebran
    ORDER BY
    annee_prec ASC
    `;
const queryC3Exception = `
    SELECT CAT.libebran,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE)-2 THEN ( PROD.AFFNOUVELLE + PROD.RENOUVELLEMENT ) ELSE 0 END) AS annee_en_cours,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE)-3 THEN ( PROD.AFFNOUVELLE + PROD.RENOUVELLEMENT ) ELSE 0 END) AS annee_prec
    FROM
      FAIT_PRODUCTION PROD, DIM_CATEGORIE CAT, DIM_DATE d 
    WHERE
        PROD.CATEGORIE_KEY = CAT.CATEGORIE_KEY
        AND PROD.DATE_KEY = d.DATE_KEY
        AND D.MOIS <= 12
    GROUP BY
        CAT.libebran
    ORDER BY
    annee_prec ASC
    `;
const queryC4 = `
    SELECT D.ANNEE, D.LIBMOIS, CAT.LIBECATE, INTER.LIBTYPIN ,  sum( ( PROD.AFFNOUVELLE + PROD.RENOUVELLEMENT )  )  as s
    FROM FAIT_PRODUCTION PROD, DIM_INTERMEDIAIRE inter, DIM_CATEGORIE cat, DIM_DATE d
    WHERE PROD.CATEGORIE_KEY = CAT.CATEGORIE_KEY
    AND PROD.INTERMEDIAIRE_KEY = INTER.INTERMEDIAIRE_KEY
    AND  PROD.DATE_KEY =  D.DATE_KEY
    AND D.MOIS < EXTRACT (MONTH from CURRENT_DATE)
    AND D.ANNEE = EXTRACT (YEAR FROM CURRENT_DATE) -1
    GROUP BY D.ANNEE, D.LIBMOIS, CAT.LIBECATE, INTER.LIBTYPIN
    ORDER BY s desc
    `;
const queryC4Exception = `
    SELECT D.ANNEE, D.LIBMOIS, CAT.LIBECATE, INTER.LIBTYPIN , sum( ( PROD.AFFNOUVELLE + PROD.RENOUVELLEMENT ))  as s
    FROM FAIT_PRODUCTION PROD, DIM_INTERMEDIAIRE inter, DIM_CATEGORIE cat, DIM_DATE d
    WHERE PROD.CATEGORIE_KEY = CAT.CATEGORIE_KEY
    AND PROD.INTERMEDIAIRE_KEY = INTER.INTERMEDIAIRE_KEY
    AND  PROD.DATE_KEY =  D.DATE_KEY
    AND D.MOIS <= 12
    AND D.ANNEE = EXTRACT (YEAR FROM CURRENT_DATE) -2
    GROUP BY D.ANNEE, D.LIBMOIS, CAT.LIBECATE, INTER.LIBTYPIN
    ORDER BY s desc
    `;
const queryC5 = `
    SELECT ((annee_en_cours - annee_prec) / annee_prec) AS pourcentage
    FROM (
      SELECT
        SUM(CASE WHEN D.ANNEE = EXTRACT (YEAR FROM CURRENT_DATE) -1 THEN ( PROD.AFFNOUVELLE + PROD.RENOUVELLEMENT )  ELSE 0 END) AS annee_en_cours,
        SUM(CASE WHEN D.ANNEE =  EXTRACT (YEAR FROM CURRENT_DATE) - 2 THEN ( PROD.AFFNOUVELLE + PROD.RENOUVELLEMENT ) ELSE 0 END) AS annee_prec
        FROM
        FAIT_PRODUCTION PROD, DIM_DATE D
        WHERE
        PROD.DATE_KEY = D.DATE_KEY
        AND D.MOIS < EXTRACT (MONTH from CURRENT_DATE)
        )`;
const queryC5Exception = `
    SELECT ((annee_en_cours - annee_prec) / annee_prec) AS pourcentage
    FROM (
    SELECT
    SUM(CASE WHEN D.ANNEE = EXTRACT (YEAR FROM CURRENT_DATE) -2 THEN ( PROD.AFFNOUVELLE + PROD.RENOUVELLEMENT )  ELSE 0 END) AS annee_en_cours,
    SUM(CASE WHEN D.ANNEE =  EXTRACT (YEAR FROM CURRENT_DATE) - 3 THEN ( PROD.AFFNOUVELLE + PROD.RENOUVELLEMENT ) ELSE 0 END) AS annee_prec
    FROM
    FAIT_PRODUCTION PROD, DIM_DATE D
    WHERE
    PROD.DATE_KEY = D.DATE_KEY
    AND D.MOIS <= 12  
    )
    `;
/* =================================     MOIS       ============================= */

const queryC1Mois = `
    SELECT
    SUM(CASE WHEN D.ANNEE = EXTRACT (YEAR FROM CURRENT_DATE) -1 THEN ( PROD.AFFNOUVELLE + PROD.RENOUVELLEMENT ) ELSE 0 END) AS annee_en_cours,
    SUM(CASE WHEN D.ANNEE =  EXTRACT (YEAR FROM CURRENT_DATE) - 2 THEN ( PROD.AFFNOUVELLE + PROD.RENOUVELLEMENT ) ELSE 0 END) AS annee_prec
    FROM
    FAIT_PRODUCTION PROD, DIM_DATE D
    WHERE
    PROD.DATE_KEY = D.DATE_KEY
    AND D.MOIS = EXTRACT(MONTH FROM CURRENT_DATE) - 1
    `;
const queryC1MoisException = `
    SELECT
    SUM(CASE WHEN D.ANNEE = EXTRACT (YEAR FROM CURRENT_DATE) -2 THEN ( PROD.AFFNOUVELLE + PROD.RENOUVELLEMENT )   ELSE 0 END) AS annee_en_cours,
    SUM(CASE WHEN D.ANNEE =  EXTRACT (YEAR FROM CURRENT_DATE) - 3 THEN ( PROD.AFFNOUVELLE + PROD.RENOUVELLEMENT )  ELSE 0 END) AS annee_prec
    FROM
    FAIT_PRODUCTION PROD, DIM_DATE D
    WHERE
    PROD.DATE_KEY = D.DATE_KEY
    AND D.MOIS = 12
    `;
const queryC2Mois = `
    SELECT
    INTER.LIBTYPIN,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE) - 1 THEN ( PROD.AFFNOUVELLE + PROD.RENOUVELLEMENT )  ELSE 0 END) AS annee_en_cours,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE) - 2 THEN ( PROD.AFFNOUVELLE + PROD.RENOUVELLEMENT ) ELSE 0 END) AS annee_prec
    FROM
        FAIT_PRODUCTION PROD, DIM_INTERMEDIAIRE inter, DIM_DATE d
    WHERE
        PROD.INTERMEDIAIRE_KEY = INTER.INTERMEDIAIRE_KEY
        AND PROD.DATE_KEY = d.DATE_KEY
        AND D.MOIS = EXTRACT(MONTH FROM CURRENT_DATE) - 1
    GROUP BY
        INTER.LIBTYPIN
    ORDER BY
        annee_prec DESC
    `;
const queryC2MoisException = `
    SELECT
    INTER.LIBTYPIN,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE) -2 THEN ( PROD.AFFNOUVELLE + PROD.RENOUVELLEMENT )  ELSE 0 END) AS annee_en_cours,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE)-3 THEN ( PROD.AFFNOUVELLE + PROD.RENOUVELLEMENT ) ELSE 0 END) AS annee_prec
    FROM
        FAIT_PRODUCTION PROD, DIM_INTERMEDIAIRE inter, DIM_DATE d
    WHERE
        PROD.INTERMEDIAIRE_KEY = INTER.INTERMEDIAIRE_KEY
        AND PROD.DATE_KEY = d.DATE_KEY
        AND D.MOIS = 12
    GROUP BY
        INTER.LIBTYPIN
    ORDER BY
        annee_prec DESC
    `;
const queryC3Mois = `
    SELECT CAT.libebran,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE) -1 THEN ( PROD.AFFNOUVELLE + PROD.RENOUVELLEMENT )  ELSE 0 END) AS annee_en_cours,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE)-2 THEN ( PROD.AFFNOUVELLE + PROD.RENOUVELLEMENT )  ELSE 0 END) AS annee_prec
    FROM
        FAIT_PRODUCTION PROD, DIM_CATEGORIE CAT, DIM_DATE d 
    WHERE
        PROD.CATEGORIE_KEY = CAT.CATEGORIE_KEY
        AND PROD.DATE_KEY = d.DATE_KEY
        AND D.MOIS = EXTRACT (MONTH FROM CURRENT_DATE ) -1
    GROUP BY
        CAT.libebran
    ORDER BY
    annee_prec ASC
    `;
const queryC3MoisException = `
    SELECT CAT.libebran,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE)-2 THEN ( PROD.AFFNOUVELLE + PROD.RENOUVELLEMENT )  ELSE 0 END) AS annee_en_cours,
    SUM(CASE WHEN D.ANNEE = EXTRACT(YEAR FROM CURRENT_DATE)-3 THEN ( PROD.AFFNOUVELLE + PROD.RENOUVELLEMENT ) ELSE 0 END) AS annee_prec
    FROM
        FAIT_PRODUCTION PROD, DIM_CATEGORIE CAT, DIM_DATE d 
    WHERE
        PROD.CATEGORIE_KEY = CAT.CATEGORIE_KEY
        AND PROD.DATE_KEY = d.DATE_KEY
        AND D.MOIS = 12
    GROUP BY
        CAT.libebran
    ORDER BY
    annee_prec ASC
    `;
const queryC4Mois = `
    SELECT D.ANNEE, D.LIBMOIS, CAT.LIBECATE, INTER.LIBTYPIN ,  sum( ( PROD.AFFNOUVELLE + PROD.RENOUVELLEMENT )  )  as s
    FROM FAIT_PRODUCTION PROD, DIM_INTERMEDIAIRE inter, DIM_CATEGORIE cat, DIM_DATE d
    WHERE PROD.CATEGORIE_KEY = CAT.CATEGORIE_KEY
    AND PROD.INTERMEDIAIRE_KEY = INTER.INTERMEDIAIRE_KEY
    AND  PROD.DATE_KEY =  D.DATE_KEY
    AND D.MOIS = EXTRACT (MONTH from CURRENT_DATE) -1
    AND D.ANNEE = EXTRACT (YEAR FROM CURRENT_DATE) -1
    GROUP BY D.ANNEE, D.LIBMOIS, CAT.LIBECATE, INTER.LIBTYPIN
    ORDER BY s desc 
    `;
const queryC4MoisException = `
    SELECT D.ANNEE, D.LIBMOIS, CAT.LIBECATE, INTER.LIBTYPIN , sum( ( PROD.AFFNOUVELLE + PROD.RENOUVELLEMENT ) )  as s
    FROM FAIT_PRODUCTION PROD, DIM_INTERMEDIAIRE inter, DIM_CATEGORIE cat, DIM_DATE d
    WHERE PROD.CATEGORIE_KEY = CAT.CATEGORIE_KEY
    AND PROD.INTERMEDIAIRE_KEY = INTER.INTERMEDIAIRE_KEY
    AND  PROD.DATE_KEY =  D.DATE_KEY
    AND D.MOIS = 12
    AND D.ANNEE = EXTRACT (YEAR FROM CURRENT_DATE) -2
    GROUP BY D.ANNEE, D.LIBMOIS, CAT.LIBECATE, INTER.LIBTYPIN
    ORDER BY s desc
    `;
const queryC5Mois = `
    SELECT ((annee_en_cours - annee_prec) / annee_prec) AS pourcentage
    FROM (
       SELECT
        SUM(CASE WHEN D.ANNEE = EXTRACT (YEAR FROM CURRENT_DATE) -1 THEN ( PROD.AFFNOUVELLE + PROD.RENOUVELLEMENT )  ELSE 0 END) AS annee_en_cours,
        SUM(CASE WHEN D.ANNEE =  EXTRACT (YEAR FROM CURRENT_DATE) - 2 THEN ( PROD.AFFNOUVELLE + PROD.RENOUVELLEMENT ) ELSE 0 END) AS annee_prec
        FROM
        FAIT_PRODUCTION PROD, DIM_DATE D
        WHERE
        PROD.DATE_KEY = D.DATE_KEY
        AND D.MOIS = EXTRACT (MONTH from CURRENT_DATE) -1
        )`;
const queryC5MoisException = `
    SELECT ((annee_en_cours - annee_prec) / annee_prec) AS pourcentage
    FROM (
    SELECT
    SUM(CASE WHEN D.ANNEE = EXTRACT (YEAR FROM CURRENT_DATE) -2 THEN ( PROD.AFFNOUVELLE + PROD.RENOUVELLEMENT )  ELSE 0 END) AS annee_en_cours,
    SUM(CASE WHEN D.ANNEE =  EXTRACT (YEAR FROM CURRENT_DATE) - 3 THEN ( PROD.AFFNOUVELLE + PROD.RENOUVELLEMENT ) ELSE 0 END) AS annee_prec
    FROM
    FAIT_PRODUCTION PROD, DIM_DATE D
    WHERE
    PROD.DATE_KEY = D.DATE_KEY
    AND D.MOIS = 12  
    )
    `;

    
module.exports={queryR1, queryR1Exception, queryR2, queryR2Exception, queryR3, queryR3Exception , queryR4, queryR4Exception,
                queryR1Mois, queryR1MoisException, queryR2Mois, queryR2MoisException, queryR3Mois, queryR3MoisException , queryR4Mois, queryR4MoisException,
                queryR5, queryR5Exception, queryR5Mois, queryR5MoisException, 
                queryCA1,
                queryCA1Exception,
                queryCA2,
                queryCA2Exception,
                queryCA3,
                queryCA3Exception,
                queryCA4,
                queryCA4Exception,
                queryCA1Mois,
                queryCA1MoisException,
                queryCA2Mois,
                queryCA2MoisException,
                queryCA3Mois,
                queryCA3MoisException,
                queryCA4Mois,
                queryCA4MoisException,
                queryCA5,
                queryCA5Exception,
                queryCA5Mois,
                queryCA5MoisException,  
                queryC1,
                queryC1Exception,
                queryC2,
                queryC2Exception,
                queryC3,
                queryC3Exception,
                queryC4,
                queryC4Exception,
                queryC1Mois,
                queryC1MoisException,
                queryC2Mois,
                queryC2MoisException,
                queryC3Mois,
                queryC3MoisException,
                queryC4Mois,
                queryC4MoisException,
                queryC5,
                queryC5Exception,
                queryC5Mois,
                queryC5MoisException,}


